/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import AFD_202103718.AFD;
import ERRORES_202103718.usoER;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import AFD_202103718.dbAFD;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringReader;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author harry
 */
public class Menu extends javax.swing.JFrame {

    /*public static String hola() {
        System.out.println("s");
        String text = "hola";
        return text;
    }*/
    
    public Menu() {
        initComponents();
        setTitle("EXREGAN Usac");
        this.setLocationRelativeTo(this);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileChooser = new javax.swing.JFileChooser();
        txt_archivo = new java.awt.TextArea();
        nombreArchivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_consola = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        botones = new javax.swing.JPanel();
        btn_analizar = new java.awt.Button();
        btn_generarAutomata = new java.awt.Button();
        eleccion = new javax.swing.JPanel();
        btn_cargaAFD = new javax.swing.JButton();
        jListaAFD = new javax.swing.JComboBox<>();
        lbl_errores = new javax.swing.JLabel();
        BarraMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        FileChooser.getAccessibleContext().setAccessibleName("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setBackground(new java.awt.Color(102, 0, 51));
        setName("frame"); // NOI18N

        nombreArchivo.setText("Archivo...");

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(900, 93));

        jt_consola.setBackground(new java.awt.Color(51, 51, 51));
        jt_consola.setColumns(20);
        jt_consola.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jt_consola.setForeground(new java.awt.Color(153, 153, 153));
        jt_consola.setRows(5);
        jt_consola.setDisabledTextColor(new java.awt.Color(204, 204, 0));
        jt_consola.setEnabled(false);
        jt_consola.setPreferredSize(new java.awt.Dimension(910, 200));
        jScrollPane1.setViewportView(jt_consola);
        jt_consola.getAccessibleContext().setAccessibleParent(jScrollPane1);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Consola");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botones.setBackground(new java.awt.Color(233, 228, 205));
        botones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_analizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_analizar.setLabel("Analizar");
        btn_analizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_analizarActionPerformed(evt);
            }
        });

        btn_generarAutomata.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_generarAutomata.setLabel("Archivo de salida");
        btn_generarAutomata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarAutomataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botonesLayout = new javax.swing.GroupLayout(botones);
        botones.setLayout(botonesLayout);
        botonesLayout.setHorizontalGroup(
            botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonesLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_analizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_generarAutomata, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        botonesLayout.setVerticalGroup(
            botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btn_generarAutomata, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_analizar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btn_generarAutomata.getAccessibleContext().setAccessibleName("generarAutomata");

        eleccion.setBackground(new java.awt.Color(233, 228, 205));
        eleccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_cargaAFD.setBackground(new java.awt.Color(240, 240, 240));
        btn_cargaAFD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_cargaAFD.setForeground(new java.awt.Color(0, 0, 0));
        btn_cargaAFD.setText("Cargar AFD'S");
        btn_cargaAFD.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_cargaAFD.setBorderPainted(false);
        btn_cargaAFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargaAFDActionPerformed(evt);
            }
        });

        jListaAFD.setBackground(new java.awt.Color(108, 22, 64));
        jListaAFD.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jListaAFD.setForeground(new java.awt.Color(246, 245, 246));
        jListaAFD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione AFD" }));
        jListaAFD.setToolTipText("");
        jListaAFD.setRequestFocusEnabled(false);
        jListaAFD.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jListaAFDItemStateChanged(evt);
            }
        });
        jListaAFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListaAFDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eleccionLayout = new javax.swing.GroupLayout(eleccion);
        eleccion.setLayout(eleccionLayout);
        eleccionLayout.setHorizontalGroup(
            eleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eleccionLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(btn_cargaAFD, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(eleccionLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jListaAFD, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        eleccionLayout.setVerticalGroup(
            eleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eleccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_cargaAFD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jListaAFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Nuevo archivo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenuItem1.getAccessibleContext().setAccessibleName("nuevoArchivo");

        jMenuItem2.setText("Abrir archivo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        BarraMenu.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(255, 51, 51));
        jMenu2.setText("Editar/Guardar");

        jMenuItem3.setText("Guardar Como");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Guardar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        BarraMenu.add(jMenu2);

        jMenu3.setText("Salir");

        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        BarraMenu.add(jMenu3);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nombreArchivo)
                .addGap(381, 381, 381))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(173, 173, 173)
                        .addComponent(lbl_errores, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_archivo, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(nombreArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(eleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lbl_errores, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //Nuevo Archivo
        txt_archivo.setText("");
        nombreArchivo.setText("Archivo...");
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        //Boton Salir
        int salir = JOptionPane.showConfirmDialog(rootPane, "¿Estas seguro que deseas salir?");
        
        if(JOptionPane.OK_OPTION == salir){
            System.exit(0);
        }
        else{
            if(JOptionPane.CANCEL_OPTION == salir){
                return;
            }
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    
    private void btn_generarAutomataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarAutomataActionPerformed
        dbAFD.jsonSalida(nameARC);
        dbAFD.cleanReporteJson();
    }//GEN-LAST:event_btn_generarAutomataActionPerformed

    private void btn_analizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_analizarActionPerformed
       String textoNuevo = RETURNtext();
       System.out.println(textoNuevo);
       
       try{
            Analizador.parser parse;
            parse = new Analizador.parser(new Analizador.Lexer(new StringReader(textoNuevo)));
            
            parse.parse();
            String muestra = "";
            int i = 1;
            
            for(String muestraC: dbAFD.muestraEnConsola()){
                muestra += muestraC;
            }
            jt_consola.setText(muestra);
            dbAFD.cleanList();          
        }
        catch(Exception ex){
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);

        }
    }//GEN-LAST:event_btn_analizarActionPerformed
    
    private static String nameARC = "";
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //ABRIR ARCHIVO
        JFileChooser fc = new JFileChooser();
        
        //FILTRO DE ARCHIVOS
        FileNameExtensionFilter fil = new FileNameExtensionFilter("Archivo olc", "olc");
        fc.setFileFilter(fil);
        
        int seleccion = fc.showOpenDialog(this);
        
        if(seleccion == FileChooser.APPROVE_OPTION){
            File fichero = fc.getSelectedFile();
            nameARC = fichero.getName();
            this.nombreArchivo.setText(fichero.getAbsolutePath());

            try(FileReader fr = new FileReader(fichero)){
                String cadena = "";
                int val = fr.read();
                while (val != -1){
                    cadena = cadena + (char) val;
                    val = fr.read();
                }
                
                this.txt_archivo.setText(cadena);
                
            } catch(IOException el){
                el.printStackTrace();
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        //GUARDAR COMO
        JFileChooser fc = new JFileChooser();
        
        
        int seleccion = fc.showSaveDialog(this);
        
        if(seleccion == JFileChooser.APPROVE_OPTION){
            File fichero = fc.getSelectedFile();
            
            try(FileWriter fw = new FileWriter(fichero+".olc")){
                fw.write(this.txt_archivo.getText());
                
                JOptionPane.showMessageDialog(null, "Archivo guardado correctamente!");
            } catch(IOException el){
                el.printStackTrace();
            }
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // GUARDAR
        
        if(nombreArchivo.getText().equals("Archivo...")){
            JFileChooser fc = new JFileChooser();
        
            int seleccion = fc.showSaveDialog(this);

            if(seleccion == JFileChooser.APPROVE_OPTION){
                File fichero = fc.getSelectedFile();

                try(FileWriter fw = new FileWriter(fichero+".olc")){
                    fw.write(this.txt_archivo.getText());
                    JOptionPane.showMessageDialog(null, "Archivo guardado correctamente!");
                } catch(IOException el){
                    el.printStackTrace();
                }
        }
        }else{
            File archivo = new File(nombreArchivo.getText());
       
            try{
               PrintWriter salida = new PrintWriter(archivo);
               salida.println(txt_archivo.getText());
               salida.close();

            }catch (FileNotFoundException ex){
               ex.printStackTrace(System.out);
            }
        
        }
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    private void btn_cargaAFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargaAFDActionPerformed

        List<AFD> lista = dbAFD.returnDatosInterfaz();
        
        for(AFD data: lista){
            jListaAFD.addItem(data.getNombre());
        }
    }//GEN-LAST:event_btn_cargaAFDActionPerformed

    private void jListaAFDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jListaAFDItemStateChanged
        // TODO add your handling code here:        
    }//GEN-LAST:event_jListaAFDItemStateChanged

    private void jListaAFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListaAFDActionPerformed
        // TODO add your handling code here:
        if(jListaAFD.getSelectedIndex()>-1){
            String salida = jListaAFD.getSelectedItem().toString();

            grafos ventanasec = new grafos();
            this.setVisible(false);
            ventanasec.nombreDeBusqueda(salida);
            ventanasec.setVisible(true);
        }
        
    }//GEN-LAST:event_jListaAFDActionPerformed

    public static void main(String args[]) {
               
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
        
        
    }
    
    public String RETURNtext(){
        String texto = this.txt_archivo.getText();
        return texto;
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JPanel botones;
    private java.awt.Button btn_analizar;
    private javax.swing.JButton btn_cargaAFD;
    private java.awt.Button btn_generarAutomata;
    private javax.swing.JPanel eleccion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> jListaAFD;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jt_consola;
    private javax.swing.JLabel lbl_errores;
    private javax.swing.JLabel nombreArchivo;
    private java.awt.TextArea txt_archivo;
    // End of variables declaration//GEN-END:variables
}
