/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author harry
 */
public class Pautomatas extends javax.swing.JPanel {

    /**
     * Creates new form Pautomatas
     */
    public Pautomatas() {
        initComponents();
    }
    
    public void asignarImageAutomata(String nombreImage){
        
        ImageIcon imagen = new ImageIcon("src/main/java/AFD_202103718/"+nombreImage+".jpg");
        int ancho = imagen.getIconWidth();
        
        
        Icon miIcono = new ImageIcon(imagen.getImage().getScaledInstance(ancho, 358, Image.SCALE_DEFAULT));
        lbl_imageN.setIcon(miIcono);
        
        
        
        ImageIcon imagenAFND = new ImageIcon("src/main/java/AFND_202103718/"+nombreImage+".jpg");
        int anchoAFND = imagenAFND.getIconWidth();
        
        
        Icon miIconoAFND = new ImageIcon(imagenAFND.getImage().getScaledInstance(anchoAFND, 303, Image.SCALE_DEFAULT));
        lbl_afnd.setIcon(miIconoAFND);
        
        
        this.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bg = new javax.swing.JPanel();
        lbl_imageN = new javax.swing.JLabel();
        lbl_afnd = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 153, 153));
        bg.setPreferredSize(new java.awt.Dimension(4000, 900));

        lbl_imageN.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_imageN, javax.swing.GroupLayout.PREFERRED_SIZE, 3850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_afnd, javax.swing.GroupLayout.PREFERRED_SIZE, 3999, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(lbl_imageN, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_afnd, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 233, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(bg);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1155, 680));
        jScrollPane1.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_afnd;
    private javax.swing.JLabel lbl_imageN;
    // End of variables declaration//GEN-END:variables
}
