/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author harry
 */
public class Ptransiciones extends javax.swing.JPanel {

    /**
     * Creates new form Ptransiciones
     */
    public Ptransiciones() {
        
        initComponents();
        
        /*ImageIcon imagen = new ImageIcon("src/main/java/TRANSICIONES_202103718/EXPreg.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(780, 640, Image.SCALE_DEFAULT));
        lbl_image.setIcon(icono);
        this.repaint();*/
    }
    
    public void asignarImagenn(String nombreImage){
        ImageIcon imagen = new ImageIcon("src/main/java/TRANSICIONES_202103718/"+nombreImage+".jpg");
        
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(780, 640, Image.SCALE_DEFAULT));
        lbl_image.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        lbl_image = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(204, 255, 153));

        lbl_image.setForeground(new java.awt.Color(0, 0, 0));
        lbl_image.setToolTipText("");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_image, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_image, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 640));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel lbl_image;
    // End of variables declaration//GEN-END:variables
}
