
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LETMIN = 18;
  public static final int LETMAY = 17;
  public static final int GUION = 5;
  public static final int S_MAS = 12;
  public static final int CONCAT = 8;
  public static final int VARIABLE = 19;
  public static final int PORCENT = 11;
  public static final int TILDE = 20;
  public static final int DP = 4;
  public static final int COMA = 22;
  public static final int SIMB = 16;
  public static final int S_UNA = 13;
  public static final int MAYOR = 6;
  public static final int EOF = 0;
  public static final int KLEEN = 10;
  public static final int DISYUN = 9;
  public static final int error = 1;
  public static final int LLAVE_C = 14;
  public static final int STR = 15;
  public static final int NCONJ = 2;
  public static final int LLAVE_A = 3;
  public static final int PC = 7;
  public static final int DIG = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NCONJ",
  "LLAVE_A",
  "DP",
  "GUION",
  "MAYOR",
  "PC",
  "CONCAT",
  "DISYUN",
  "KLEEN",
  "PORCENT",
  "S_MAS",
  "S_UNA",
  "LLAVE_C",
  "STR",
  "SIMB",
  "LETMAY",
  "LETMIN",
  "VARIABLE",
  "TILDE",
  "DIG",
  "COMA"
  };
}

